# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartCQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='smartCQ.Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='entity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='smartCQ.Entity'),
        ),
    ]
