# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCQ', '0004_auto_20160819_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='entity',
        ),
        migrations.AddField(
            model_name='question',
            name='entity',
            field=models.ManyToManyField(blank=True, null=True, to='smartCQ.Entity'),
        ),
    ]
