# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartCQ', '0006_auto_20160820_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='question',
            name='intent',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
