# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCQ', '0008_auto_20160820_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='entity',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='entity',
        ),
        migrations.AddField(
            model_name='question',
            name='entity',
            field=models.ManyToManyField(blank=True, null=True, to='smartCQ.Entity'),
        ),
    ]
