# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCQ', '0009_auto_20160820_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='question',
            name='intent',
        ),
        migrations.AddField(
            model_name='answer',
            name='entity',
            field=models.ManyToManyField(blank=True, null=True, to='smartCQ.Entity'),
        ),
        migrations.AddField(
            model_name='answer',
            name='intent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
